require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*
    - node_modules/**/*

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*
    - lib/tasks/**/*.rake

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

