AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: [describe] # excludes RSpec.describe
