require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: [describe] # excludes RSpec.describe
