# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98345aaecb3b379d98ad585a725023deef2fc7ac4181f8a171449a025d053fc0dcac78f22bbc8ba1c77fe88b6e59cbe1e56e2b8979027e285842da727d25b8f3

test:
  secret_key_base: 3a16dddba2c4bc2fc395345295bb50956ef5f688cb40e9ac096484113de25404df9df0f7464e39e790a51a20afe89f3559f9897ccc2e2beed8bf7d23e10ff452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
