schedule:
  ProcessScheduledContributions:
    every: '10s'
  SendContributionReminders:
    every: '10m'
  ProcessFailedContributions:
    cron: '0 0 5 * * *'
  ProcessDonationPlans:
    cron: '0 0 10 * * *'
