schedule:
  ProcessScheduledContributions:
    interval: '1h'
  SendContributionReminders:
    interval: '4h'
  ProcessFailedContributions:
    interval: '1h'
  ScheduleContributionsForPastDuePlans:
    interval: '30m'